[profile.default]
solc_version="0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
revert_strings = "strip"
isolate = true

ffi = true
src = "test"
out = "artifacts/foundry"
script = "scripts"
cache_path = "cache/foundry"
fs_permissions = [{ access = "read", path = "./deployments" }]
verbosity = 3

[fmt]
tab_width = 2
bracket_spacing = true
number_underscore = "thousands"

[profile.production.fuzz]
runs = 66_666

[profile.overkill.fuzz]
runs = 6_666_666
